apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: clue2solve
spec:
  portal:
    title: Workshops @ Clue2solve.io   
    registration:
      type: anonymous
  workshops:
  - name: knative-fundamentals
    capacity: 2
    expires: 30m
    orphaned: 5m
