apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-markdown-sample
spec:
  title: Knative Fundamentals
  description: A Self paced workshop to walk you through the basics of Knative Serving
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/clue2solve/knative-fundamentals-workshop
  content:
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    files: github.com/clue2solve/knative-fundamentals-workshop
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
