apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: knative-fundamentals
spec:
  title: "Knative Fundamentals"
  description: A Self paced workshop to walk you through the basics of Knative Serving
  vendor: clue2solve.io
  authors:
  - Anand Rao
  difficulty: intermediate
  duration: 30m
  url: https://github.com/clue2solve/knative-fundamentals-workshop
  tags:
  - kubernetes
  - knative
  - k8s
  content:
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    files: github.com/clue2solve/knative-fundamentals-workshop
  session:
    namespaces:
      budget: medium
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
